// const movies = [
//     {
//       id: 1,
//       title: 'Inception',
//       synopsis: 'A thief who steals corporate secrets by using dream-sharing technology.',
//       cast: 'Leonardo DiCaprio, Joseph Gordon-Levitt',
//       crew: 'Christopher Nolan',
//       releaseDate: '2010-07-06',
//       duration: 148,
//       imagePath: './src/assets/clapperboard.png',
//     },
//     {
//       id: 2,
//       title: 'The Dark Knight',
//       synopsis: 'Batman sets out to dismantle the remaining criminal organizations.',
//       cast: 'Christian Bale, Heath Ledger',
//       cast: 'Christopher Nolan',
//       releaseDate: '2008-07-18',
//       duration: 152,
//       imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 3,
//         title: 'Pulp Fiction',
//         synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
//         cast: 'John Travolta, Uma Thurman',
//         crew: 'Quentin Tarantino',
//         releaseDate: '1994-10-14',
//         duration: 154,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 4,
//         title: 'Fight Club',
//         synopsis: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
//         cast: 'Brad Pitt, Edward Norton',
//         crew: 'David Fincher',
//         releaseDate: '2014-07-18',
//         duration: 139,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 5,
//         title: 'The shawshank Redemption',
//         synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption.',
//         cast: 'Tim Robbins, Morgan Freeman',
//         crew: 'Frank Darabont',
//         releaseDate: '1994-10-14',
//         duration: 142,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 6,
//         title: 'the Godfather',
//         synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
//         cast: 'Marlon Brando, Al Pacino',
//         crew: 'Francis Ford Coppola',
//         releaseDate: '1972-03-24',  
//         duration: 175,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 7,
//         title: 'The Matrix',
//         synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
//         cast: 'Keanu Reeves, Laurence Fishburne',
//         crew: 'Lana Wachowski, Lilly Wachowski',
//         releaseDate: '1999-03-31',
//         duration: 136,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 8,
//         title: 'Forrest Gump',
//         synopsis: 'The story of Forrest Gump, a simple man who unwittingly becomes part of key events in 20th-century America.',
//         cast: 'Tom Hanks, Robin Wright',
//         crew: 'Robert Zemeckis',
//         releaseDate: '1994-07-06',
//         duration: 142,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 9,
//         title: 'Goodfellas',
//         synopsis: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
//         cast: 'Robert De Niro, Ray Liotta',
//         crew: 'Martin Scorsese',
//         releaseDate: '1990-09-19',
//         duration: 146,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 10,
//         title: 'The Lord of the Rings: The Return of the King',
//         synopsis: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.',
//         cast: 'Elijah Wood, Viggo Mortensen',
//         crew: 'Peter Jackson',
//         releaseDate: '2003-12-17',
//         duration: 201,
//         imagePath: './src/assets/clapperboard.png',
//     },
//     {
//         id: 11,
//         title: 'The Lion King',
//         synopsis: 'A young lion prince flees his kingdom after the murder of his father.',
//         cast: 'Matthew Broderick, James Earl Jones',
//         crew: 'Roger Allers, Rob Minkoff',
//         releaseDate: '1994-06-15',
//         runtime: '88',
//         imagePath : './src/assets/clapperboard.png'
//     },
//     {
//         id: 12,
//         title: 'Titanic',
//         synopsis:'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
//         cast: 'Leonardo DiCaprio, Kate Winslet',
//         crew: 'James Cameron',
//         releaseDate: '1997-12-19',
//         runtime: '194',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 13 ,
//         title: 'Star Wars: Episode IV - A New Hope',
//         synopsis:'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire.',
//         cast: 'Mark Hamill, Harrison Ford',
//         crew: 'George Lucas',
//         releaseDate: '1977-05-25',
//         runtime: '121',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 14 ,
//         title: 'The Avengers',
//         synopsis:'Earths mightiest heroes must come together and learn to fight as a team.',
//         cast: 'Robert Downey Jr., Chris Evans',
//         crew: 'Joss Whedon',
//         releaseDate: '2012-05-04',
//         runtime: '143',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 15,
//         title: 'Jurassic Park',
//         synopsis:'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the parks cloned dinosaurs to run loose.',
//         cast: 'Sam Neill, Laura Dern',
//         crew: 'Steven Spielberg',
//         releaseDate: '1993-06-11',
//         runtime: '127',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 16,
//         title: 'The Godfather: Part II',
//         synopsis:'The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on the family crime syndicate.',
//         cast: 'Al Pacino, Robert De Niro',
//         crew: 'Francis Ford Coppola',
//         releaseDate: '1974-12-20',
//         runtime: '200',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 17,
//         title: 'The Shawshank Redemption',
//         synopsis:'Two imprisoned men bond over a number of years, finding solace and eventual redemption.',
//         cast: 'Tim Robbins, Morgan Freeman',
//         crew: 'Frank Darabont',
//         releaseDate: '1994-09-23',
//         runtime: '142',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 18,
//         title: 'Schindlers List',
//         synopsis:'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
//         cast: 'Liam Neeson, Ralph Fiennes',
//         crew: 'Steven Spielberg',
//         releaseDate: '1993-12-15',
//         runtime: '195',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 19,
//         title: 'The Dark Knight',
//         synopsis:'Batman sets out to dismantle the remaining criminal organizations.',
//         cast: 'Christian Bale, Heath Ledger',
//         crew: 'Christopher Nolan',
//         releaseDate: '2008-07-18',
//         runtime: '2008-07-18',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 20,
//         title: 'Pulp Fiction',
//         synopsis:'The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine.',
//         cast: 'John Travolta, Uma Thurman',
//         crew: 'Quentin Tarantino',
//         releaseDate: '1994-10-14',
//         runtime: '154',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 21,
//         title: 'Fight Club',
//         synopsis:'An insomniac office worker and a devil-may-care soapmaker form an underground fight club.',
//         cast: 'Brad Pitt, Edward Norton',
//         crew: 'David Fincher',
//         releaseDate: '1999-10-15',
//         runtime: '139',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:22 ,
//         title: 'Forrest Gump',
//         synopsis:'The story of Forrest Gump, a simple man who unwittingly becomes part of key events in 20th-century America.',
//         cast: 'Tom Hanks, Robin Wright',
//         crew: 'Robert Zemeckis',
//         releaseDate: '1994-07-06',
//         runtime: '142',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 23,
//         title: 'The Matrix',
//         synopsis:'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
//         cast: 'Keanu Reeves, Laurence Fishburne',
//         crew: 'Lana Wachowski, Lilly Wachowski',
//         releaseDate: '1999-03-31',
//         runtime: '136',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 24,
//         title: 'Goodfellas',
//         synopsis:'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.',
//         cast: 'Robert De Niro, Ray Liotta',
//         crew: 'Martin Scorsese',
//         releaseDate: '1990-09-19',
//         runtime: '146',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:25,
//         title: 'The Lord of the Rings: The Fellowship of the Ring',
//         synopsis:'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.',
//         cast: 'Elijah Wood, Ian McKellen',
//         crew: 'Peter Jackson',
//         releaseDate: '2001-12-19',
//         runtime: '178',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 26,
//         title: 'The Lion King',
//         synopsis:'A young lion prince flees his kingdom after the murder of his father.',
//         cast: 'Matthew Broderick, James Earl Jones',
//         crew: 'Roger Allers, Rob Minkoff',
//         releaseDate: '1994-06-15',
//         runtime: '88',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:27,
//         title: 'Titanic',
//         synopsis:'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
//         cast: 'Leonardo DiCaprio, Kate Winslet',
//         crew: 'James Cameron',
//         releaseDate: '1997-12-19',
//         runtime: '194',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:28,
//         title: 'Star Wars: Episode IV - A New Hope',
//         synopsis:'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire.',
//         cast: 'Mark Hamill, Harrison Ford',
//         crew: 'George Lucas',
//         releaseDate: '1977-05-25',
//         runtime: '121',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:29,
//         title: 'The Avengers',
//         synopsis:'Earths mightiest heroes must come together and learn to fight as a team.',
//         cast: 'Robert Downey Jr., Chris Evans',
//         crew: 'Joss Whedon',
//         releaseDate: '2012-05-04',
//         runtime: '143',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:30,
//         title: 'Jurassic Park',
//         synopsis:'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the parks cloned dinosaurs to run loose.',
//         cast: 'Sam Neill, Laura Dern',
//         crew: 'Steven Spielberg',
//         releaseDate: '1993-06-11',
//         runtime: '127',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:31,
//         title: 'Inception',
//         synopsis:'A thief who steals corporate secrets by using dream-sharing technology.',
//         cast: 'Leonardo DiCaprio, Joseph Gordon-Levitt',
//         crew: 'Christopher Nolan',
//         releaseDate: '2010-07-16',
//         runtime: '148',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:32,
//         title: 'The Godfather',
//         synopsis:'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
//         cast: 'Marlon Brando, Al Pacino',
//         crew: 'Francis Ford Coppola',
//         releaseDate: '1972-03-24',
//         runtime: '175',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:33,
//         title: 'Interstellar',
//         synopsis:'A team of explorers travels through a wormhole in space to ensure humanity survival.',
//         cast: 'Matthew McConaughey, Anne Hathaway',
//         crew: 'Christopher Nolan',
//         releaseDate: '2014-11-07',
//         runtime: '169',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:34,
//         title: 'The Social Network',
//         synopsis:'The story of the creation of Facebook and the legal battles that followed.',
//         cast: 'Jesse Eisenberg, Andrew Garfield',
//         crew: 'David Fincher',
//         releaseDate: '2010-10-01',
//         runtime: '120',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:35,
//         title: 'Gladiator',
//         synopsis:'A former Roman General seeks vengeance for the murder of his family.',
//         cast: 'Russell Crowe, Joaquin Phoenix',
//         crew: 'Ridley Scott',
//         releaseDate: '2000-05-05',
//         runtime: '155',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:36,
//         title: 'The Departed',
//         synopsis:'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
//         cast: 'Leonardo DiCaprio, Matt Damon',
//         crew: 'Martin Scorsese',
//         releaseDate: '2006-10-06',
//         runtime: '151',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:37,
//         title: 'Inglourious Basterds',
//         synopsis:'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner vengeful plans.',
//         cast: 'Brad Pitt, Christoph Waltz',
//         crew: 'Quentin Tarantino',
//         releaseDate: '2009-08-21',
//         runtime: '153',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:38,
//         title: 'Inception',
//         synopsis:'A thief who steals corporate secrets by using dream-sharing technology.',
//         cast: 'Leonardo DiCaprio, Joseph Gordon-Levitt',
//         crew: 'Christopher Nolan',
//         releaseDate: '',
//         runtime: '',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id:39,
//         title: 'The Dark Knight',
//         synopsis:'Batman sets out to dismantle the remaining criminal organizations.',
//         cast: 'Christian Bale, Heath Ledger',
//         crew: 'Christopher Nolan',
//         releaseDate: '2008-07-18',
//         runtime: '152',
//         imagePath: './src/assets/clapperboard.png'
//     },
//     {
//         id: 40,
//         title: 'Pulp Fiction',
//         synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
//         cast: 'John Travolta, Uma Thurman',
//         crew: 'Quentin Tarantino',
//         releaseDate: '1994-10-14',
//         duration: 154,
//         imagePath: './src/assets/clapperboard.png',
//     }
//   ];

//     export default movies;
  